package pe.edu.upc.upet.navigation

data object Routes {
    const val registerPet = "registerPet"
    const val Home = "home"
    const val PetList = "petList"
    const val VetList = "vetList"
    const val UserRegister = "signUpScreen"
    const val UserLogin = "signInScreen"
    const val PasswordRecovery = "sendEmailScreen"
    const val ConfirmCode = "ConfirmCodeScreen"
    const val NewPassword = "NewPasswordScreen"
    const val PostRegister = "postRegister"
    const val Profile = "profile"
    const val AppointmentList = "appointmentList"
    const val SubscriptionBasicScreen = "subscriptionBasicScreen"
    const val SubscriptionAdvancedScreen = "subscriptionAdvancedScreen"
    const val PetOwnerEditProfile = "petOwnerEditProfile"
    const val PetEdit = "PetEdit"
    const val VetProfile= "vetProfile"
    const val BookAppointmentScreen = "bookAppointmentScreen"
    const val AppointmentDetail = "appointmentDetail"
    const val PetDetailsAppointment = "petDetailsAppointment"
    const val PetMedicalInformationScreen = "petMedicalInformationScreen"
    const val NewMedicalRegisterScreen = "newMedicalRegisterScreen"
    const val NewVaccineRegister = "newVaccineRegister"
    const val NewSurgeryRegister = "newSurgeryRegister"
    const val NewTestResultRegister = "newTestResultRegister"
    const val NewDiagnosisRegister = "newDiagnosisRegister"
    const val EditVeterinaryProfile = "editVeterinaryProfile"
    const val EditVeterinaryPassword = "editVeterinaryPassword"

}